
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 12 19:17:57 CET 2011
//----------------------------------------------------

package pdlcompilerproyect;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID_VAR = 37;
  public static final int FUNCTION = 38;
  public static final int RIGHT_PAREN = 28;
  public static final int SCANF = 12;
  public static final int NUM_OCT = 8;
  public static final int EQUALS = 30;
  public static final int PROGRAMA = 2;
  public static final int RIGHT_LLAVE = 26;
  public static final int GREATER = 36;
  public static final int SEMI = 15;
  public static final int INT = 35;
  public static final int NUM_HEX = 9;
  public static final int ARRAY = 39;
  public static final int ASTERISCO = 21;
  public static final int LESS = 34;
  public static final int FOR = 6;
  public static final int CONSTANTE = 44;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int GREATER_EQUALS = 32;
  public static final int IF = 3;
  public static final int RIGHT_CORCHETE = 41;
  public static final int OF = 45;
  public static final int BOOLEAN = 43;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int SIZE = 48;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int CTE_BOOLEANA = 7;
  public static final int MENOS = 19;
  public static final int CONTAINS = 49;
  public static final int PRINTF = 13;
  public static final int ASIGNACION = 29;
  public static final int PUNTOS = 17;
  public static final int NUM_BIN = 10;
  public static final int NUM_REAL = 51;
  public static final int ELSE = 4;
  public static final int LESS_EQUALS = 33;
  public static final int WHILE = 5;
  public static final int LEFT_CORCHETE = 40;
  public static final int NOT_EQUALS = 31;
  public static final int CPRINTF = 14;
  public static final int FLOAT = 11;
  public static final int LEFT_PAREN = 27;
  public static final int NUM_ENTERO = 50;
  public static final int MALLOC = 46;
  public static final int ENTRE = 20;
  public static final int LEFT_LLAVE = 25;
  public static final int FREE = 47;
  public static final int MAS = 18;
}

